spring:
  data:
    mongodb:
      database: my-mongo
      uri: mongodb://localhost:27017/my-mongo
  application:
    name: product-service
  
server:
  port: 3002


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}

