spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      locator:
        enabled: true
      routes:

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
            
server:
  port: 2222


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5




