spring:
  datasource:
    url: jdbc:h2:tcp://localhost/C:\D\Lesson\Software_structure\aw03;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: niu
    password: 123
    driverClassName: org.h2.Driver
    initialize: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  batch:
    jdbc:
      initialize-schema: always

  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
  sql:
    init:
      platform: h2
      mode: always
      schema-locations: classpath:schema.sql

  application:
    name: spring-batch-service
