spring:
  application:
    name: delivery-service
  rabbitmq:
    rabbitmq:
      host: localhost
      port: 5672
      virtual-host: /
      username: guest
      password: guest
  

server:
  port: 1234


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}

